--- #YAML:1.0
name:               WebService-Amazon-Route53
version:            0.012
abstract:           Perl interface to Amazon Route 53 API
author:
    - Michal Wojciechowski <odyniec@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  0
    LWP::UserAgent:     0
    Test::More:         0
    Tie::IxHash:        0
    URI::Escape:        0
    XML::Simple:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
