---
abstract: 'Perl interface to Amazon Route 53 API'
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Amazon-Route53
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  LWP::UserAgent: 0
  Test::More: 0
  Tie::IxHash: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.013
